//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Убиј_го_кртот {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Убиј_го_кртот.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backgroundddd {
            get {
                object obj = ResourceManager.GetObject("backgroundddd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet {
            get {
                object obj = ResourceManager.GetObject("bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BulletHole {
            get {
                object obj = ResourceManager.GetObject("BulletHole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fireshot {
            get {
                object obj = ResourceManager.GetObject("fireshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 Martin
        ///999 Zharko
        ///777 Banderas.
        /// </summary>
        internal static string HighScore {
            get {
                return ResourceManager.GetString("HighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap killedMole {
            get {
                object obj = ResourceManager.GetObject("killedMole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mole {
            get {
                object obj = ResourceManager.GetObject("Mole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap signFinal {
            get {
                object obj = ResourceManager.GetObject("signFinal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slug1 {
            get {
                object obj = ResourceManager.GetObject("slug1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slug2 {
            get {
                object obj = ResourceManager.GetObject("slug2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slug3 {
            get {
                object obj = ResourceManager.GetObject("slug3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Target {
            get {
                object obj = ResourceManager.GetObject("Target", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ð¢Ð°ÐºÐ° Ð»Ð¸ ÑÐµ Ð¿ÑƒÐºÐ°?
        ///Ð‘Ð°Ð±Ð° Ð¼Ð¸ Ð¿Ð¾Ð±Ñ€Ð·Ð¾ ÑœÐµ Ð¼Ðµ Ð¿Ð¾Ð³Ð¾Ð´Ð¸?
        ///ÐŸÑ€Ð¾Ñ„ÐµÑÐ¸Ð¾Ð½Ð°Ð»Ð½Ð¾ Ð¸Ð·Ð±ÐµÐ³Ð½ÑƒÐ²Ð°ÑšÐµ!
        ///ÐœcGregor Ð¼Ð¾Ð¶Ðµ Ð²Ð¾Ð´Ð° Ð´Ð° Ð¼Ð¸ Ð½Ð¾ÑÐ¸!
        ///ÐšÐ¸Ð½ÐµÐ· Ð±Ð¾Ñ™Ð¸ Ñ†ÐµÐ½Ñ‚Ñ€Ð¸Ñ€Ð° Ð¾Ð´ Ñ‚ÐµÐ±Ðµ!
        ///Ð•Ñ˜, Ñ‚ÑƒÐºÐ° ÑÑƒÐ¼!
        ///ÐœÐµÑÑ‚Ð¾ ÐºÐ°Ð»ÐºÑƒÐ»ÑƒÑ 2 Ð´Ð° ÑƒÑ‡Ð¸Ñˆ!
        ///ÐŸÑ€Ð¾Ð¼Ð°ÑˆÐ¸!
        ///Ð”ÑƒÑ€ Ð¼Ðµ Ð¿Ð¾Ð³Ð¾Ð´Ð¸Ñˆ, Ð´ÐµÐºÐ°Ð½ ÑœÐµ ÑÑ‚Ð°Ð½Ð°Ð¼!
        ///ÐÐµ, Ð½Ðµ , Ñ‚ÑƒÐºÐ° ÑÑƒÐ¼!.
        /// </summary>
        internal static string TrashTalking {
            get {
                return ResourceManager.GetString("TrashTalking", resourceCulture);
            }
        }
    }
}
